#!/bin/bash -e

GRPC_VERSION=${GRPC_VERSION:-1.46}
GRPC_FULL_VERSION=${GRPC_FULL_VERSION:-1.46.0}
GRPC_VERSION_BY_RELEASE=${GRPC_VERSION_BY_RELEASE:-1.46}
GRPC_FULL_VERSION_BY_RELEASE=${GRPC_FULL_VERSION_BY_RELEASE:-1.46.0}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-1.46}
